public class myfamily {
    
    public String Owner_name ,father_name , Mother_name;
    public Integer  Owner_age , father_age,Mother_age;
    
    public void disp()
    {
       System.debug('Owner_name ='+ Owner_name);
        System.debug('father_name ='+ father_name);
        System.debug('Mother_name ='+ Mother_name);
        System.debug('Owner_age ='+ Owner_age);
        System.debug('father_age ='+ father_age);
        System.debug('Mother_age ='+ Mother_age);

    }

}